#时钟
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]

#顶层数码管显示输出
set_property IOSTANDARD LVCMOS33 [get_ports {TopNum[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNum[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNum[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNum[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNum[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNum[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNum[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNum[0]}]
set_property PACKAGE_PIN T10 [get_ports {TopNum[7]}]
set_property PACKAGE_PIN R10 [get_ports {TopNum[6]}]
set_property PACKAGE_PIN K16 [get_ports {TopNum[5]}]
set_property PACKAGE_PIN K13 [get_ports {TopNum[4]}]
set_property PACKAGE_PIN P15 [get_ports {TopNum[3]}]
set_property PACKAGE_PIN T11 [get_ports {TopNum[2]}]
set_property PACKAGE_PIN L18 [get_ports {TopNum[1]}]
set_property PACKAGE_PIN H15 [get_ports {TopNum[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNumEN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNumEN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNumEN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNumEN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNumEN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNumEN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNumEN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {TopNumEN[0]}]
set_property PACKAGE_PIN U13 [get_ports {TopNumEN[7]}]
set_property PACKAGE_PIN K2 [get_ports {TopNumEN[6]}]
set_property PACKAGE_PIN T14 [get_ports {TopNumEN[5]}]
set_property PACKAGE_PIN P14 [get_ports {TopNumEN[4]}]
set_property PACKAGE_PIN J14 [get_ports {TopNumEN[3]}]
set_property PACKAGE_PIN T9 [get_ports {TopNumEN[2]}]
set_property PACKAGE_PIN J18 [get_ports {TopNumEN[1]}]
set_property PACKAGE_PIN J17 [get_ports {TopNumEN[0]}]